---
- hosts: all
  become: true
  become_method: sudo
  become_user: root
  pre_tasks:

  - name: Update repository index (CentOS)
    tags: always
    dnf:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "CentOS"

  - name: Install updates (Ubuntu)
    tags: always
    apt:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Ubuntu"


  tasks:
    - name: Install keystone (identity service)
      apt:
        name=keystone
        state=present

    - name: Install glance (imaging service)
      apt:
        name=glance
        state=present

    - name: Install nova (compute service)
      apt:
        name=python3-nova
        state=present
